import os

PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")
PINECONE_ENV = os.getenv("PINECONE_ENV")
PINECONE_INDEX_NAME = "rulebook-ai"

CEREBRAS_API_KEY = os.getenv("CEREBRAS_API_KEY")
COHERE_API_KEY = os.getenv("COHERE_API_KEY")

CHUNK_SIZE = 500
CHUNK_OVERLAP = 100